import openpyxl
from pathlib import Path

from cm_choke import add_cm_chokes
from diode import add_diodes
from ferrite_bead import add_ferrite_beads
from fuse import add_fuses
from inductor import add_inductors
from led import add_leds
from resistor import add_resistors
from tvs_zener import add_tvs_zeners
from capacitor import add_capacitors

SOURCE_FILE = "autogenerated_parts.xlsx"
LIBRARY_DIR = Path("../..")


def main():
    workbook = openpyxl.load_workbook(SOURCE_FILE)
    for sheet_name, lib_func in [
        ("capacitor", add_capacitors),
        ("cm_choke", add_cm_chokes),
        ("diode", add_diodes),
        ("ferrite_bead", add_ferrite_beads),
        ("fuse", add_fuses),
        ("inductor", add_inductors),
        ("led", add_leds),
        ("resistor", add_resistors),
        ("tvs_zener", add_tvs_zeners),
    ]:
        lib_func(LIBRARY_DIR, workbook[sheet_name].values)


if __name__ == "__main__":
    main()
